### ISSUE TITLE
Components missing 

### ISSUE THREAD

**Issue by rebejones22** [LuiseFreese/FluentUI-for-Teams#1]
Hello. I am not seeing the Power App or the components mentioned like the drop-down box. Only seeing the animated gifs.

**Comment by LuiseFreese** [comment]
hey Rebecca, I assume you attended my session at CollabDaysNL, in which I referred to https://github.com/pnp/powerapps-samples/tree/main/samples/fluentui-for-teams-theme

This repo is just for my personal docs.
